<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Username_identifier</name>
   <tag></tag>
   <elementGuidId>51c3210b-1a24-4e29-9d7b-ee573b38ad3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#identifier-field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identifier-field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>00846b33-89bc-4442-a1c5-6d897d2c3461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cl-formFieldInput cl-formFieldInput__identifier cl-required 🔒️ cl-internal-mdg29y</value>
      <webElementGuid>671afac7-23d0-48e9-a176-fd34e3608455</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>identifier</value>
      <webElementGuid>a0ec809a-7cbe-4080-bb08-90fab288867d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dac7e5c3-d671-42d0-a8b3-3cfe94823739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>action</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>3b0f9181-8773-4fa1-801d-efd18fc1d402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifier-field</value>
      <webElementGuid>8f00df49-ad0a-4034-b5ab-58a478c0e4ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0e47c029-7a13-49c3-8605-c251b2161900</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2409a7e0-7300-4572-bbf8-cab6ad27a5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifier-field&quot;)</value>
      <webElementGuid>2929db1a-d62f-4224-9e31-81263cb44ffe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identifier-field']</value>
      <webElementGuid>4fcdb561-1321-4cc0-9e82-07bda3d8bec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>4ec49e78-97f5-4a42-963b-80f5a86b1547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'identifier' and @type = 'text' and @id = 'identifier-field']</value>
      <webElementGuid>dcf14462-9651-4bbf-a8e3-f61c5eb9574d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
